theme: jekyll-theme-tactile
relative_links:
  enabled: true
  collections: true
github:
  is_project_page: false
  is_user_page: false
description: Nicholas McKinney
show_downloads: false
defaults:
  -
    scope:
      path: ""
    values:
      layout: post
      title:  Technical Documentation
