theme: jekyll-theme-dinky
relative_links:
  enabled: true
  collections: true
github:
  is_project_page: false
  is_user_page: false
title: rooted
description: Nicholas McKinney
show_downloads: false
defaults:
  -
    scope:
      path: ""
    values:
      layout: post
      title:  j0rn3y_sec
